server {
    listen 443 ssl;
    server_name painel-admin.laetonline.org;

    ssl_certificate     /etc/nginx/certs/painel-admin.laetonline.org_ecc/fullchain.cer;
    ssl_certificate_key /etc/nginx/certs/painel-admin.laetonline.org_ecc/painel-admin.laetonline.org.key;
    
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;

    location / {
    if ($request_method = 'OPTIONS') {
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
        add_header Access-Control-Allow-Headers "Authorization,Content-Type";
        add_header Content-Length 0;
        add_header Content-Type text/plain;
        return 204;
    }

    try_files $uri $uri/ /index.html;

    add_header Access-Control-Allow-Origin "*" always;
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Authorization,Content-Type" always;
}
    
}